### ISSUE TITLE
Just FYI, Seems StrawPoll may have changed something.

### ISSUE THREAD

**Issue by Mahsaap** [swiftyspiffy/StrawPollNET#1]
The actual call now fails with badresponse. Haven't dug in to it yet. But I would assume Strawpoll has changed something on their end.

**Comment by Mahsaap** [comment]
// Create the poll
StrawpollNET.Models.CreatedPoll newPoll = new StrawPollNET.API.Create.CreatePoll(pollTitle, allOptions, multipleChoice, dupCheck, requireCaptcha);

for example fails

**Comment by swiftyspiffy** [comment]
Will check that now.

Seems to be an underlying issue with Strawpoll.me. Relevant tweet: https://twitter.com/swiftyspiffy/status/981616623332163585

**Comment by Mahsaap** [comment]
Fixed
